### ISSUE TITLE
Joshua's critique on Divya's site

### ISSUE THREAD

**Issue by b-joshua** [divz-k/divz-k.github.io#1]
Great website, Divya! I especially love the picture of the panda. You should add a link to your lab in the section where you talk about your academic journey. It would also be nice for you to list some publications if you have any.
When you link to the Institute and to the lecturer's page, it would be nice to include a brief description of what is found at each link.
Your site has a clear and visually appealing layout. Well done.

**Comment by divz-k** [comment]
thank you!
